name: C/C++ CI

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Build project with CMAKE
      uses: lpenz/ghaction-cmake@v0.1
    - name: GH Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')  
      with:
        files: |
          DBImporter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
     
    steps:    
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Build project with CMAKE
      uses: lpenz/ghaction-cmake@v0.1
    - name: GH Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          DBImporter.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
