name: C/C++ CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build project with CMAKE
      uses: lpenz/ghaction-cmake@v0.1
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Release.txt
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
